[tool.poetry]
name = "unetplusplus-coronary-artery-calcium-scoring-segmentation"
version = "0.1.0"
description = ""
authors = ["Aditya Wardianto <83759122+ditw11mhs@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
tensorflow = "^2.9.1"
numpy = "^1.22.4"
streamlit = "^1.10.0"
pydicom = "^2.3.0"
python-dotenv = "^0.20.0"
plotly = "^5.8.2"
matplotlib = "^3.5.2"

[tool.poetry.dev-dependencies]
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
